# Packages and Modules 
- Set of funtions called Modules
- Multiple set of Modules called Packages
    - In built 
    - User defiend 
- import the all packages with help of "import" keyword
- it is just known as one python file  

In [2]:
#In built packages 
import math as m
#from math import sqrt 
m.floor(4.5)


4

In [3]:
m.ceil(4.5)

5

In [4]:
dir(m)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [5]:
import random as r

dir(r)


['BPF',
 'LOG4',
 'NV_MAGICCONST',
 'RECIP_BPF',
 'Random',
 'SG_MAGICCONST',
 'SystemRandom',
 'TWOPI',
 '_BuiltinMethodType',
 '_MethodType',
 '_Sequence',
 '_Set',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_acos',
 '_bisect',
 '_ceil',
 '_cos',
 '_e',
 '_exp',
 '_inst',
 '_itertools',
 '_log',
 '_os',
 '_pi',
 '_random',
 '_sha512',
 '_sin',
 '_sqrt',
 '_test',
 '_test_generator',
 '_urandom',
 '_warn',
 'betavariate',
 'choice',
 'choices',
 'expovariate',
 'gammavariate',
 'gauss',
 'getrandbits',
 'getstate',
 'lognormvariate',
 'normalvariate',
 'paretovariate',
 'randint',
 'random',
 'randrange',
 'sample',
 'seed',
 'setstate',
 'shuffle',
 'triangular',
 'uniform',
 'vonmisesvariate',
 'weibullvariate']

In [15]:
def getRandomNUmbers(lb,ub):
    for i in range(1,11):
        print(r.randint(lb,ub),end=" ")
lb=1
ub=10
getRandomNUmbers(lb,ub)

10 6 8 9 1 5 9 1 7 6 

In [ ]:
#User defined  packages 

In [19]:
def isPrimeNumber(n):
    if n<2:
        return False
    for i in range(2,(n//2)+1):
        if n%i==0:
            return False
    return True
isPrimeNumber(23)

True

In [23]:
import mypackage as m
# m.isPrimeNumber(47)
def generateAllPrimeNumbers(lb,ub):
    for i in range(lb,ub+1):
        if m.isPrimeNumber(i):
            print(i,end=" ")
generateAllPrimeNumbers(1,100)
            
    

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [35]:
import mypackage 
mypackage.isPrimeNumber(13)

True

## Regular Expressions
* It is also one type of Programming language 
* It is also called pattern matching technic by using symbols 
* [] - character set ex.[a-zA-Z0-9]
* ^  - starting letter 
* $  - ending letter 
* {} - range set 
* .  - zero char set 
* *  - can multiply
* |  - OR 
* +  - Concatination
* for doing regular expressions we need to import the "re"
        


In [36]:
import re 

print(dir(re))

['A', 'ASCII', 'DEBUG', 'DOTALL', 'I', 'IGNORECASE', 'L', 'LOCALE', 'M', 'MULTILINE', 'Match', 'Pattern', 'RegexFlag', 'S', 'Scanner', 'T', 'TEMPLATE', 'U', 'UNICODE', 'VERBOSE', 'X', '_MAXCACHE', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_cache', '_compile', '_compile_repl', '_expand', '_locale', '_pickle', '_special_chars_map', '_subx', 'compile', 'copyreg', 'enum', 'error', 'escape', 'findall', 'finditer', 'fullmatch', 'functools', 'match', 'purge', 'search', 'split', 'sre_compile', 'sre_parse', 'sub', 'subn', 'template']


In [38]:
#Match()
 #it is match the pattern/symbol
re.match("c","cbit")

<re.Match object; span=(0, 1), match='c'>

In [39]:
re.match("i","cbit")#It only match the first char 


In [42]:
#Search
re.search("i","cbiti")#It will match only one letter/chr  

<re.Match object; span=(2, 3), match='i'>

In [43]:
#FindAll
re.findall("i","cbiti")

['i', 'i']

In [44]:
re.findall("s","sapssdcs")

['s', 's', 's', 's']

In [ ]:
#Single Digit number matching
    #^[0-9]$
# Match the three digit number 
    #^[0-9]{3}$
# Match paticular char 
    #[5]|[4]|[%]|[$]|[#]
#match the eight digit number starting with 8 and 
                                    #ending with 2
"""    ->81234432(valid)
    ->89876542(valid)
    ->312345679(invalid)"""
    #^[8][0-9]{6}[2]$
#Mobile number validation starting with 6 or 7 or 8 or 9 
    #^[6-9][0-9]{9}$
    #^[0][6-9][0-9]{9}$ -->starting with zero
    #^[+][9][1][6-9][0-9]{9}$  -->Starting with +91 
# Email validation
    #3 parts(example@mail.com)
    #1.username len(8 to 15)
    #2.domain len(gmail,apssdc,yahoo,outlook,ksrm,cbit..etc)[4-7]
    #3.Extention (.com,.in,.org,.ac.in,edu,co.in..etc)[2-4]
        #^[a-zA-Z0-9]{1}[a-zA-z0-9._-]{7,15}[@][a-z]{4,7}[.][a-z]{2,4}$

In [60]:
#Funtion to validate the mobile number
import re 

pattern="^[6-9][0-9]{9}$|^[0][6-9][0-9]{9}$|^[+][9][1][6-9][0-9]{9}$"
def isValidMobileNumber(mobile_number):
    if re.match(pattern,mobile_number):
        print(mobile_number,"  is Valid Number")
    else:
        print(mobile_number," is Invalid Number please try again")
# mobile_number=input('Enter the mobile number')
# isValidMobileNumber(mobile_number)
test_cases=int(input("Enter no of Test Cases:"))
for i in range(test_cases):
    mobile_number=input("Enter Mobile number:")
    isValidMobileNumber(mobile_number)
    

Enter no of Test Cases:5
Enter Mobile number:123456789
123456789  is Invalid Number please try again
Enter Mobile number:987654321
987654321  is Invalid Number please try again
Enter Mobile number:9876543210
9876543210   is Valid Number
Enter Mobile number:+919876543210
+919876543210   is Valid Number
Enter Mobile number:8325698745
8325698745   is Valid Number


In [53]:
isPrimeNumber(7)

True

In [58]:
def rangeprimenumbers(lb,ub):
    for i in range(lb,ub+1):
        if(isPrimeNumber(i)):
            print(i,end=" ")
rangeprimenumbers(40,100)

41 43 47 53 59 61 67 71 73 79 83 89 97 

In [59]:
test_cases=int(input())
for i in range(test_cases):
    lb=int(input())
    ub=int(input())
    rangeprimenumbers(lb,ub)

5
10
20
11 13 17 19 20
40
23 29 31 37 30
50
31 37 41 43 47 60
70
61 67 80
90
83 89 

In [10]:
#List comprahension
s="hanuman"
m=[]
for i in s:
    m.append(i)
print(m)

    

['h', 'a', 'n', 'u', 'm', 'a', 'n']


In [8]:
m1=[i for i in s ] 
print(m1)
l2="".join(m1)
l2


['h', 'a', 'n', 'u', 'm', 'a', 'n']


'hanuman'

In [2]:
fp='file.txt'

In [12]:
fp='file.txt'
def getfileData(fp):
    with open(fp,'r') as f:
        fd=f.read()
        print(fd)
getfileData(fp)

hi hello
how are you 



In [15]:
def countLines(fp):
    c=0
    with open(fp,"r") as f:
        for i in f:
            c=c+1
        return c
countLines(fp)
            

2

In [4]:
with open(fp,"r") as f:
    fd=f.readlines()#it will return the list of words
    s="".join(fd)
    print(s)
    s1,c=0,0
    for i in s:
        c=c+1
        print(c,"-->",i,end=" ")

hi hello
how are you 

1 --> h 2 --> i 3 -->   4 --> h 5 --> e 6 --> l 7 --> l 8 --> o 9 --> 
 10 --> h 11 --> o 12 --> w 13 -->   14 --> a 15 --> r 16 --> e 17 -->   18 --> y 19 --> o 20 --> u 21 -->   22 --> 
 

In [30]:
with open(fp,"r") as f:
    fd=f.read()
    words=fd.split()
    print(words)
    print(len(words))

['hi', 'hello', 'how', 'are', 'you']
5


In [31]:
import numpy as np

d=np.arange(1000)
print(d.size*d.itemsize)

4000


In [42]:
s2=np.arange(1000)
print(s2.size*s2.itemsize)
# print(list(s2))

4000


In [41]:
import sys

e=range(0,1000)
print(sys.getsizeof(e)*len(e))
# print(list(e))


48000


In [43]:
oneD=np.array([1,2,5,3])
oneD

array([1, 2, 5, 3])

In [77]:
#Addition for one D
print("Additon of one D is ",oneD+1)
print("squreing of one D is ",oneD**2)
print("mul of one D is ",oneD*10)
# oneD *=2
# print("modifying of one D is ",oneD)
print("original of one D is ",oneD)
a=np.array([[1,2,3],[3,4,5],[9,6,0]])
print("\noriginal of two D is \n",a)
print("Transpose of two  D is\n ",a.T)

Additon of one D is  [ 5  9 21 13]
squreing of one D is  [ 16  64 400 144]
mul of one D is  [ 40  80 200 120]
original of one D is  [ 4  8 20 12]

original of two D is 
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of two  D is
  [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [49]:
twoD=np.random.randint(10,size=(3,4))
twoD

array([[2, 7, 3, 5],
       [7, 8, 0, 8],
       [2, 4, 1, 1]])

In [64]:
mulD=np.random.randint(10,size=(3,4,4))
mulD[2]

array([[6, 2, 8, 3],
       [2, 0, 1, 8],
       [8, 2, 6, 1],
       [5, 0, 8, 2]])

In [58]:
fv=np.zeros((2,4))
fv

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
nn=np.arange(1,10,1)
nn

array([1, 2, 3, 4, 5, 6, 7, 8, 9])