# List Comprahension
* reducing number of coding iteration

In [3]:
n="hanuman"
el=[]
for i in n:
    el.append(i)
print(el)

['h', 'a', 'n', 'u', 'm', 'a', 'n']


In [5]:
#by using list comprahenstion
n="Hanuman"
nl=[i for i in n ]
nl

['H', 'a', 'n', 'u', 'm', 'a', 'n']

In [10]:
#Converting list to string
nn="".join(nl)
nn

'Hanuman'

In [11]:
#First 1 to 10 natural numbers 
li=[num for num in range(1,11)]
li

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
even=[e for e in range(1,11) if e%2==0 ]
even

[2, 4, 6, 8, 10]

In [14]:
#Generate the all yeap years by using list comp..
lb,ub=2000,2020
allLeapYeasrs=[year for year in range(lb,ub+1) if (year%400==0 or (year%100!=0 and year%4==0))]
allLeapYeasrs

[2000, 2004, 2008, 2012, 2016, 2020]

In [ ]:
#Task 
# Generte all prime numbers 1000 to 2000 using list comrahenstion

# Files in Python
- To Store the data 
- .pdf,.exe,.txt,.doc...etc
- read/write/append/ 

In [15]:
filepath='DataFolder/mydata.txt'

## we have modes in file data processing
### read() --r
### write() --w
### append() --a
### Create() --x

In [16]:
#open()
with open(filepath,'r') as f:
    filedata=f.read()
    print(filedata)

Jai pubg
winner winner chicken dinner 
cod
coin master 
ludo



In [17]:
#Write data into files 
with open(filepath,'w') as f:
    fdata_write=f.write("APSSDC")
    print(fdata_write)

6


In [18]:
#Append mode
with open(filepath,'a') as f:
    fdata_write=f.write("\nCbit")
    print(fdata_write)

5


In [29]:
#read,readLine and readlines
with open(filepath,'r') as f:
    filedata=f.read()# it will get the only one line from the file
#     filedata1=f.readline()
#     filedata2=f.readlines()
#     print("Read lines :",filedata1)
#     print("Read Line :",filedata2)
    print("Read :\n",filedata)

Read :
 APSSDC
Cbit


In [40]:
#Read the all lines present in the file
with open(filepath,'r') as f:
    countLines=0
    for i in f:
        countLines=countLines+1
        print(i)
    print("Nuber of lines in the file :",countLines)
        #         print(i)     
    
    

APSSDC

Cbit

muni

A text file is a type of digital, non-executable file that contains letters, numbers, symbols and/or a combination.

It enables the creation and storage of text without any special formatting.

Text files are also known as flat files or ASCII files
Nuber of lines in the file : 6


In [43]:
#calculating total words in the file
with open(filepath,'r') as f:
    fd=f.read()
    word=fd.split(" ")
    print("The total words are :",len(word))
    print(word)
    

The total words are : 39
['APSSDC\nCbit\nmuni\nA', 'text', 'file', 'is', 'a', 'type', 'of', 'digital,', 'non-executable', 'file', 'that', 'contains', 'letters,', 'numbers,', 'symbols', 'and/or', 'a', 'combination.\nIt', 'enables', 'the', 'creation', 'and', 'storage', 'of', 'text', 'without', 'any', 'special', 'formatting.\nText', 'files', 'are', 'also', 'known', 'as', 'flat', 'files', 'or', 'ASCII', 'files']


In [60]:
#Char count
with open(filepath,'r') as f:
    fd=f.read()
    chrCount="".join(fd)
#     print(chrCount)
    c=0
    sc=0
    for i in chrCount:
        if(i!=' '):
            c=c+1
#             print(c,"-->",i)
        else:
            sc+=1
    print("Total Chars are : ",c,end="")
    print("\nSpaces Count :",sc)
    print("Total Characters in File:",c+sc)
        
    

Total Chars are :  225
Spaces Count : 38
Total Characters in File: 263


# Data Science
* Numpy->Numarical Python 
    - it is more efficent 
    - it takes less storage space 
    - it is faster then python list
* Pandas
* Matplot Lib

In [63]:
#
import numpy as np

num=np.arange(1,1001)
print("Total size is :",num.size*num.itemsize)
print(list(num))


Total size is : 4000
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 2

In [66]:
# python list
import sys

listNumbers=range(1,1001)
print(sys.getsizeof(listNumbers)*len(listNumbers))
print(list(listNumbers))

48000
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 2

In [68]:
# Numpy one dimentional Array Decalration
one_D=np.array([1,3,4,5,6])
one_D

array([1, 3, 4, 5, 6])

In [73]:
a=2
print("adding of 2 is in oneD :",one_D+a)
print("Multiply of 5 :",one_D*5)
print("squring of oneD is :",one_D**2)


adding of 2 is in oneD : [3 5 6 7 8]
Multiply of 5 : [ 5 15 20 25 30]
squring of oneD is : [ 1  9 16 25 36]


In [69]:
li=[1,4,8,3]
a=2
print("Addtionof a and list is",li+a)
# 3,6,10,5



TypeError: can only concatenate list (not "int") to list

In [95]:
### 2-D Arr[]
tD=np.random.randint(10,size=(4,3))+1
tD


array([[ 1,  2, 10],
       [ 2,  2,  1],
       [ 4,  5,  1],
       [ 8,  2, 10]])

In [94]:
print("first row is ",tD[0])#Getting first row
print("1st row and 1st column :",tD[1][1])
print(tD[1:])

first row is  [ 5 10  9]
1st row and 1st column : 5
[[ 2  5  9]
 [10  2  4]
 [ 1  3 10]]


In [78]:
#Multi_D arr[]
mD=np.random.randint(10,size=(3,4,3))
mD

array([[[5, 1, 4],
        [9, 5, 0],
        [2, 0, 8],
        [1, 6, 2]],

       [[6, 8, 5],
        [0, 1, 4],
        [2, 7, 3],
        [6, 5, 2]],

       [[9, 8, 3],
        [9, 7, 3],
        [5, 3, 8],
        [3, 9, 5]]])

In [79]:
mD[1]

array([[6, 8, 5],
       [0, 1, 4],
       [2, 7, 3],
       [6, 5, 2]])

## http://tiny.cc/x6iqez

In [100]:
n=np.zeros((3,4))
n

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
n1=np.ones((2,6))
n1

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [1]:
import pandas as pd
i_data=pd.read_csv('income.csv')
i_data

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [ ]:
182p5a0246.cbit@apssdc.info