## Data Science 
* Numpy
    - NumPy (Numerical Python) is a linear algebra library in Python. It is a very important library on which almost every <b>data science or machine learning </b>Python packages such as SciPy (Scientific Python), Mat−plotlib (plotting library), Scikit-learn, etc depends on to a reasonable extent.
    - NumPy is <b>very useful for performing mathematical and logical operations on Arrays</b>. It provides an abundance of useful features for operations on n-arrays and matrices in Python.
* Pandas 


#how to create NumPy arrays
##### This Workshop covers basics things to know about NumPy as a beginner in Data science. These includes how to create NumPy arrays, use broadcasting, access values, and manipulate arrays. More importantly, you will learn NumPy’s benefit over Python lists, which include: being more compact, faster access in reading and writing items, being more convenient and more efficient.

In [2]:
# To Create a NumPy Arrays
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [3]:
#We can simply create a NumPy array called my_numpy_list and display the result:
import numpy as np

mynumpy_list=np.array(my_list)
mynumpy_list


array([1, 2, 3, 4, 5])

In [4]:
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Array Indexing: Accessing Single Elements

In [10]:
b=np.random.randint(0,1,size=(3,3,3,3))
b[2][2][2][1]

0

In [11]:
b.ndim

4

In [16]:
print()

[array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]), array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]), array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])]

In [17]:
s=np.random.seed(0)  # seed for reproducibility
s

In [24]:
oneDimentionalarr=np.random.randint(10,size=6)# For Generate one dimentional array
oneDimentionalarr

array([5, 0, 2, 3, 8, 1])

In [26]:
twoDimentionalArray=np.random.randint(10,size=(3,4) ) # For Generating two dimentional array
twoDimentionalArray

array([[3, 3, 3, 7],
       [0, 1, 9, 9],
       [0, 4, 7, 3]])

In [27]:
threeDimentionalArray=np.random.randint(10,size=(3,4,5)) #for generating Four Dimentional array
threeDimentionalArray

array([[[2, 7, 2, 0, 0],
        [4, 5, 5, 6, 8],
        [4, 1, 4, 9, 8],
        [1, 1, 7, 9, 9]],

       [[3, 6, 7, 2, 0],
        [3, 5, 9, 4, 4],
        [6, 4, 4, 3, 4],
        [4, 8, 4, 3, 7]],

       [[5, 5, 0, 1, 5],
        [9, 3, 0, 5, 0],
        [1, 2, 4, 2, 0],
        [3, 2, 0, 7, 5]]])

In [33]:
threeDimentionalArray[1]

array([[3, 6, 7, 2, 0],
       [3, 5, 9, 4, 4],
       [6, 4, 4, 3, 4],
       [4, 8, 4, 3, 7]])

In [29]:
oneDimentionalarr[0]

5

In [35]:
twoDimentionalArray[2,2]

7

In [36]:
twoDimentionalArray[2,-1]

3

In [37]:
twoDimentionalArray[0,0]=12
twoDimentionalArray

array([[12,  3,  3,  7],
       [ 0,  1,  9,  9],
       [ 0,  4,  7,  3]])

In [ ]:
#https://github.com/Akash-Sinha/PythonDataScienceHandbook/blob/master/notebooks/02.02-The-Basics-Of-NumPy-Arrays.ipynb

### One-dimensional subarray


In [38]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x[:4]#Firsr Five Elememts

array([0, 1, 2, 3])

In [41]:
x[4:]# After four elememts 

array([4, 5, 6, 7, 8, 9])

In [42]:
x[::2] #Every other element

array([0, 2, 4, 6, 8])

In [44]:
x[1::3]

array([1, 4, 7])

## Multi-dimensional subarrays
Multi-dimensional slices work in the same way, with multiple slices separated by commas. For example:

In [48]:
x2=twoDimentionalArray
x2

array([[12,  3,  3,  7],
       [ 0,  1,  9,  9],
       [ 0,  4,  7,  3]])

In [49]:
x2[:2,:3] #two rows ,three colums 

array([[12,  3,  3],
       [ 0,  1,  9]])

In [50]:
x2[:1,:2]

array([[12,  3]])

In [51]:
x2[:3,::2]

array([[12,  3],
       [ 0,  9],
       [ 0,  7]])

## Pandas 
* Python has long been great for data munging (the process of changing data into another format)and preparation, but less so for data analysis and modeling. pandas helps fill this gap, enabling you to carry out your entire data analysis workflow in Python without having to switch to a more domain specific language like R.

In [55]:
import pandas as pd

internal1={'s1':22,'s2':18,'s3':12}
internal1=pd.Series(internal1)
internal1

s1    22
s2    18
s3    12
dtype: int64

In [56]:
internal2={'s1':23,'s2':12,'s3':19}
internal2=pd.Series(internal2)
internal2

s1    23
s2    12
s3    19
dtype: int64

In [57]:
    final={'Internal1':internal1,'Internal2':internal2}
    final=pd.DataFrame(final)
    final

Internal1  Internal2
s1         22         23
s2         18         12
s3         12         19

In [58]:
final.columns

Index(['Internal1', 'Internal2'], dtype='object')

In [59]:
final.values

array([[22, 23],
       [18, 12],
       [12, 19]], dtype=int64)

In [60]:
final.values[2]

array([12, 19], dtype=int64)

In [64]:
final.values[2,0]

12

In [65]:
for i in final.values:
    print('Internal 1-',i[0],"Internal 2-",i[1])

Internal 1- 22 Internal 2- 23
Internal 1- 18 Internal 2- 12
Internal 1- 12 Internal 2- 19


In [80]:
final.loc['s3']=[15,8]
final

Internal1  Internal2
s1         22         23
s2         18         12
s3         15          8

In [78]:
final=final.drop(5)
final


Internal1  Internal2
s1         22         23
s2         18         12

In [75]:
final

Internal1  Internal2
s1         22         23
s2         18         12
s3         12         19
5          15          8
4          15          8

In [6]:
s='3084585028jojihk9498725983586'
allEven=''
allOdd=''
for i in s:
    if i.isalpha():
        print(i,end=' ')
    elif int(i)% 2==0:
        allEven=allEven +i
    else:
        allOdd=allOdd +i
print('\n',allEven)
print('\n',allOdd)
        
    
        

j o j i h k 
 0848028482886

 3559975935


In [16]:
pi='python'
l=len(pi)
if l%2==0:
    print((pi[len(pi)//2-1]),pi[len(pi)//2])
else:
    print(pi[len(pi)//2])
    

t h


In [21]:
n=10
c=0
for i in range(1,11):
    c=c+1
    print(n,'x',c,'=',n*i)

10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100


In [26]:
#perfect number
def isperfect(n):
    s=0
    for i in range(1,n):
        if n%i==0:
            s=s+i
    if s==n:
        return True
    else:
        return False
n=int(input())
isperfect(n)
            

28


True

In [27]:
t=(1,2,3,'apssdc')
t

(1, 2, 3, 'apssdc')

In [1]:
import ipaddress

ipaddress.ip_address('192.168.1.2')

IPv4Address('192.168.1.2')

In [2]:
ipaddress.ip_address('2001:af3::')

IPv6Address('2001:af3::')